/*
 * JosmMCPPlugin - JOSM plugin to integrate JOSM with the Model Context Protocol
 * Copyright (C) 2025-2026 Pengunaria.dev
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.openstreetmap.josm.plugins.josmmcp;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import org.junit.jupiter.api.Test;

/**
 * A Claude Code skill can carry a full copy of the client-neutral guide, so that an agent
 * has it in context without a second file read. That copy is generated by
 * {@code tools/sync-agent-skill.py} and is not tracked in this repository; when it exists,
 * this test keeps it honest. Edit {@code docs/agent-guide/README.md}, then re-run the script.
 */
class AgentGuideTest {
	private static final Path GUIDE = Path.of("docs", "agent-guide", "README.md");
	private static final Path SKILL = Path.of(".claude", "skills", "osm-mapping", "SKILL.md");

	/** Links are sibling-relative in the guide and repository-root-relative in the skill. */
	private static final String[][] REWRITES = {
			{"josmmcp-tools.md", "docs/agent-guide/josmmcp-tools.md"},
			{"osm-wiki.md", "docs/agent-guide/osm-wiki.md"},
			{"dutch-sources.md", "docs/agent-guide/dutch-sources.md"},
			{"../../README.md", "README.md"},
	};

	private static String read(Path p) throws IOException {
		return new String(Files.readAllBytes(p), StandardCharsets.UTF_8);
	}

	@Test
	void skillIsAnUpToDateCopyOfTheGuide() throws IOException {
		assumeTrue(Files.isRegularFile(SKILL), "no generated skill copy in this working tree");
		String guide = read(GUIDE);
		for (String[] r : REWRITES) {
			guide = guide.replace(r[0], r[1]);
		}

		String skill = read(SKILL);
		assertTrue(skill.startsWith("---\n"), "the skill needs YAML frontmatter");
		int end = skill.indexOf("\n---\n", 4);
		assertTrue(end > 0, "the skill's frontmatter is not closed");
		String frontmatter = skill.substring(4, end);
		assertTrue(frontmatter.contains("name: osm-mapping"), "the skill must keep its name");
		assertTrue(frontmatter.contains("description:"), "the skill must keep its description");

		String body = skill.substring(end + "\n---\n".length()).stripLeading();
		assertEquals(guide, body,
				"SKILL.md no longer matches docs/agent-guide/README.md; run tools/sync-agent-skill.py");
	}

	@Test
	void everyCompanionFileTheGuideNamesExists() throws IOException {
		String guide = read(GUIDE);
		for (String name : List.of("josmmcp-tools.md", "osm-wiki.md", "dutch-sources.md")) {
			assertTrue(guide.contains(name), "the guide should point at " + name);
			assertTrue(Files.isRegularFile(GUIDE.resolveSibling(name)), name + " is missing");
		}
	}
}
